export const FETCH_GIPHS = 'FETCH_GIPHS'
export const FETCH_MORE_GIPHS_SUCCESS = 'FETCH_MORE_GIPHS_SUCCESS'
export const FETCH_MORE_GIPHS_ERROR = 'FETCH_MORE_GIPHS_ERROR'

export const ORDER_BY = 'ORDER_BY'

export const IS_FETCHING = 'IS_FETCHING'
export const ON_SUCCESS = 'ON_SUCCESS'
export const ON_ERROR = 'ON_ERROR'
